app/routes.py
import os
import json
import config
from app.db import Database
from app.keys import KeyRing
from app.geo import search_places
from app.image import save_image
from app.labels import LabelManager
from flask_caching import Cache
from flask_sse import sse
from datetime import datetime, timezone, timedelta
from flask import Blueprint, abort, request, render_template, jsonify, send_from_directory

bp = Blueprint('main', __name__)
kr = KeyRing(config.KEYS_FILE)
db = Database(config.DB_PATH)
lm = LabelManager(config.LABELS_PATH)
cache = Cache(config=config.CACHE)


def get_conf(loc):
    try:
        return config.LOCATIONS[loc]
    except KeyError:
        abort(404)


@bp.route('/')
def index():
    if hasattr(config, 'DEFAULT_LOCATION'):
        location = config.DEFAULT_LOCATION
        conf = get_conf(location)
        return render_template('map.html', conf=conf, location=location)
    else:
        # List all live locations
        return render_template('index.html',
                locations=[k for k in config.LOCATIONS.keys()
                    if config.LOCATIONS[k]['LIVE']])


@bp.route('/version')
@cache.cached(timeout=600)
def version():
    return jsonify(version=config.VERSION)


@bp.route('/<location>/')
def map(location):
    conf = get_conf(location)
    return render_template('map.html', conf=conf, location=location)

@bp.route('/<location>/labels')
def labels(location):
    labels = {
        k: v['icon'] for k, v in lm.labels(location).items()
        if not v['hide']
    }
    return jsonify(labels=labels)

@bp.route('/<location>/log/<type>', methods=['GET', 'POST'])
@cache.cached(timeout=5,
              unless=lambda: request.method != 'GET',
              make_cache_key=lambda *args, **kwargs: '{}_{}'.format(
                  request.path,
                  request.headers.get('X-AUTH', 'noauth')))
def log(location, type):
    conf = get_conf(location)
    key = request.headers.get('X-AUTH')
    auth = kr.check_key(key, location)

    if request.method == 'POST':
        if not auth: abort(401)

        # Admin logs can't be updated this way
        if type == 'admin': abort(400)

        # Grab submitted log data
        data = request.form.to_dict()

        # If an image was submitted, save it
        if request.files.get('image'):
            filename = save_image(request.files['image'])
            if filename is None:
                abort(400)
            data['image'] = filename

        # Add the log data
        db.add(type, location, key, data)

        # Clear cache so new requests get latest data
        cache.clear()

        # Ping clients to grab latest data
        timestamp = datetime.utcnow().replace(tzinfo=timezone.utc).timestamp()
        sse.publish(json.dumps(
            {'data': data, 'timestamp': timestamp}), channel=location)
        return jsonify(success=True)
    else:

        # Admin logs can't be updated this way
        if type == 'admin':
            abort(400)
        elif type == 'event':
            # Limit amount of event logs that are sent
            now = datetime.utcnow().replace(tzinfo=timezone.utc)
            if config.LOGS_AFTER is None:
                logs = db.logs(location, n=config.MAX_LOGS, type='event')
            else:
                interval = (now - timedelta(**config.LOGS_AFTER)).timestamp()
                logs = db.logs(location, n=config.MAX_LOGS, after=interval, type='event')
        elif type == 'pinned':
            # For pinned, only return latest
            logs = db.logs(location, n=1, type='pinned')
        else:
            logs = db.logs(location, type=type)

        # Strip submitter info
        # Check permissions
        for l in logs:
            submitter = l.pop('submitter')
            if auth and (auth == 'prime' or key.startswith(submitter)):
                l['permit'] = True
        return jsonify(logs=logs)


@bp.route('/<location>/log/<type>/all')
@cache.cached(timeout=5)
def all_logs(location, type):
    conf = get_conf(location)

    # Admin logs can't be read this way
    if type == 'admin': abort(400)

    logs = db.logs(location, type=type)

    # Strip submitter info
    # Check permissions
    for l in logs:
        l.pop('submitter')
    return jsonify(logs=logs)


@bp.route('/<location>/log/edit', methods=['POST'])
def edit_log(location):
    key = request.headers.get('X-AUTH')
    auth = kr.check_key(key, location)

    # Abort if not authed at all
    if not auth:
        abort(401)

    if request.method == 'POST':
        data = request.get_json()
        action = data['action']
        timestamp = data['timestamp']

        # See if a log matches the request
        log = db.log(location, timestamp)
        if log is None: abort(404)

        # Admin logs can't be edited
        if log['type'] == 'admin': abort(400)

        # Abort if not prime key or not submitter
        if auth == 'prime' or key == log['submitter']:
            if action == 'delete':
                db.delete(location, timestamp)
                cache.clear()
                sse.publish('delete' , channel=location)
                return jsonify(success=True)

            elif action == 'update':
                for k, v in data['changes'].items():
                    log['data'][k] = v
                db.update(location, timestamp, log['data'])
                cache.clear()
                sse.publish('update' , channel=location)
                return jsonify(success=True)
            return jsonify(success=False, error='Unknown action')
        else:
            abort(401)
    return jsonify(success=False)

# Get a list of possible lat/lngs for a location query
@bp.route('/<location>/location', methods=['POST'])
def query_location(location):
    conf = get_conf(location)
    key = request.headers.get('X-AUTH')
    if not kr.check_key(key, location):
        abort(401)
    data = request.get_json()
    results = search_places(data['query'], conf)
    return jsonify(results=results)

@bp.route('/img/<fname>')
def image(fname):
    return send_from_directory(os.path.join('..', config.UPLOAD_PATH), fname)


# Panel (key management backend)
@bp.route('/<location>/panel')
def panel(location):
    conf = get_conf(location)
    return render_template('panel.html', conf=conf, location=location)


@bp.route('/<location>/panel/logs')
def admin_logs(location):
    key = request.headers.get('X-AUTH')
    if not kr.check_key(key, location) == 'prime':
        abort(401)
    admin_logs = db.logs(location, type='admin')
    pinned_logs = db.logs(location, type='pinned')
    logs = sorted(admin_logs + pinned_logs, key=lambda l: l['timestamp'])
    return jsonify(logs=logs)


@bp.route('/<location>/panel/keys', methods=['GET', 'POST'])
def keys(location):
    key = request.headers.get('X-AUTH')
    if not kr.check_key(key, location) == 'prime':
        abort(401)

    if request.method == 'POST':
        data = request.get_json()
        action = data['action']
        if action == 'revoke':
            kr.del_key(location, data['key'])
            db.add('admin', location, key, {
                'type': 'keys',
                'action': action,
                'target': {
                    'key': data['key'],
                }
            })
            return jsonify(success=True)
        elif action == 'create':
            new_key = kr.new_key()
            typ = data.get('type', 'write')
            kr.add_key(location, new_key, typ)
            db.add('admin', location, key, {
                'type': 'keys',
                'action': action,
                'target': {
                    'type': typ,
                    'key': new_key,
                }
            })
            return jsonify(success=True, key=new_key)
        return jsonify(success=False)

    keys = kr.get_keys(location)
    return jsonify(keys=keys)


@bp.route('/<location>/panel/labels', methods=['GET', 'POST'])
def panel_labels(location):
    key = request.headers.get('X-AUTH')
    if not kr.check_key(key, location) == 'prime':
        abort(401)

    if request.method == 'POST':
        data = request.get_json()
        action = data['action']
        if action == 'hide':
            label = data['label']
            success = lm.hide(location, label)
            if success:
                db.add('admin', location, key, {
                    'type': 'labels',
                    'action': action,
                    'target': {
                        'label': label,
                    }
                })
            return jsonify(success=success)
        elif action == 'unhide':
            label = data['label']
            success = lm.unhide(location, label)
            if success:
                db.add('admin', location, key, {
                    'type': 'labels',
                    'action': action,
                    'target': {
                        'label': label,
                    }
                })
            return jsonify(success=success)
        elif action == 'edit':
            icon = data['icon']
            label = data['label']
            success = lm.edit_icon(location, label, icon)
            if success:
                db.add('admin', location, key, {
                    'type': 'labels',
                    'action': action,
                    'target': {
                        'label': label,
                        'icon': icon,
                    }
                })
            return jsonify(success=success)
        elif action == 'create':
            icon = data['icon']
            label = data['label']
            success = lm.create(location, label, icon)
            if success:
                db.add('admin', location, key, {
                    'type': 'labels',
                    'action': action,
                    'target': {
                        'label': label,
                        'icon': icon,
                    }
                })
            return jsonify(success=success)

templates/index.html
{% extends 'layout.html' %}

{% block content %}
<div id="listing">
    <h1>Choose your city:</h1>
    <ul>
        {% for loc in locations %}
            <li><a href="{{ url_for('main.map', location=loc) }}">{{ loc }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{{ conf.TITLE or config.TITLE or 'scanmap' }}</title>

  {% block meta %}
      <meta property="og:site_name" content="scanmap">
      <meta property="og:type" content="website">
      <meta property="og:description" content="mapping scanners">
      <meta property="og:title" content="scanmap">
      <meta name="twitter:card" content="summary">
      <meta name="twitter:title" content="scanmap">
      <meta name="twitter:description" content="mapping scanners">
  {% endblock %}

  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}?{{ config.VERSION }}">
  <link rel="shortcut icon" href="/favicon.ico">

  {% block head %}
  {% endblock %}
</head>

<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/map.html
{% extends 'layout.html' %}
{% block head %}
<script src="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.js"></script>
<link href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css" rel="stylesheet" />
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.2.0/mapbox-gl-draw.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-draw/v1.2.0/mapbox-gl-draw.css' rel='stylesheet' type='text/css' />
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-language/v0.10.1/mapbox-gl-language.js'></script>
{% endblock %}

{% block content %}
<div id="stage">
    <div id="map"></div>
    <div id="bar">
        <div id="pinned-log">
            <div id="pinned-hide">x</div>
            <div id="pinned-log-text"></div>
        </div>
        <div id="log">
            <div id="log-tabs">
                <div data-type="event" class="log-tab selected" translate>Events</div>
                <div data-type="static" class="log-tab" translate>Points of Interest</div>
            </div>
            <div id="event-logs" class="logs selected">
                <div class="no-log" translate>No recent posts</div>
            </div>
            <div id="static-logs" class="logs">
                <div class="no-log" translate>No recent posts</div>
            </div>
        </div>
        <div id="info">
            <div id="info-toggle">▼</div>
            <div id="info-body">
                <div>{{ conf.INFO | safe }}</div>
                <div id="toggles">
                    {% set extras = conf.EXTRAS|default({}) %}
                    {% if extras.CAMERAS %}
                        <div id="toggle-cams"><input type="checkbox" autocomplete="off" id="cam-toggle-input"> <label for="cam-toggle-input" translate>Traffic cams</label></div>
                    {% endif %}
                    {% if extras.HELICOPTERS %}
                        <div id="toggle-helicopters"><input type="checkbox" autocomplete="off" id="helicopters-toggle-input"> <label for="helicopters-toggle-input" translate>Helicopters</label></div>
                    {% endif %}
                    {% if extras.PRECINCTS %}
                        <div id="toggle-precincts"><input type="checkbox" autocomplete="off" id="precincts-toggle-input"> <label for="precincts-toggle-input" translate>Precincts</label></div>
                    {% endif %}
                    <div id="toggle-static"><input type="checkbox" autocomplete="off" id="static-toggle-input"> <label for="static-toggle-input" translate>Points of Interest</label></div>
                </div>
                <div id="add" translate>If you have a key, click here to start adding.</div>
                <div id="legend"></div>
            </div>
        </div>
    </div>
    <div id="overlay">
        <div id="intro">
            <h2>How to help</h2>
            <ul class="help">
                <li>1. Add a note describing the report, with relevant details. For example, if people are arrested ("under"), note how many. <b>Verify as much as you can, especially if it involves shooting.</b> We don't want to spread misinformation or incite panic.</li>
                <li>2. Add a location. Add cross streets if possible.</li>
                <li>3a. Click the search icon to find possible coordinates for the location. Click on one of the results to set it.</li>
                <li>3b. Alternatively, click on the map to set the location.</li>
                <li>4. Add a label/icon so we can easily identify the activity.</li>
                <li>5. Submit. There may be a short delay before your submission appears on the map.</li>
            </ul>

            <ul>
                <li><b>Please limit to information that is useful for people on the ground.</b> We are trying to ensure that people remain safe and unharmed.</li>
                <li><b>Please keep the information related to the protests.</b> You may hear 911 chatter, which is not necessarily useful for people on the ground.</li>
                <li><b>Try to confirm information before reporting, if possible.</b> Reports of "shots fired" for instance can cause panic and need additional verification.</li>
                <li><b>Avoid mentioning identifying information about protestors.</b></li>
                <li><b>Avoid using police jargon/language and framing.</b></li>
            </p>

            <div id="intro-info">{{ conf.INFO | safe }}</div>
            <button id="ready" translate>Got it</button>
        </div>
    </div>
    <div id="auth-status"></div>
    <div id="append">
        <div id="append-tabs">
            <div data-type="event" class="append-tab selected" translate>Event</div>
            <div data-type="static" class="append-tab" translate>Point of Interest</div>
        </div>
        <div id="append-form">
            <div id="coordinates-type">
                <div>
                    <span translate>Type</span>:
                    <ul>
                        <li data-type="point" class="selected" translate>Point</li>
                        <li data-type="area" translate>Area</li>
                    </ul>
                </div>
                <div id="coordinates-type--hint">
                    <div data-type="point" class="selected" translate>Click on map to set point</div>
                    <div data-type="area" translate>Double-click to enable draw mode</div>
                </div>
            </div>
            <input id="text" type="text" placeholder="Note" />
            <div id="location-search-field">
                <input id="location" type="text" placeholder="Location" />
                <div id="location-search">🔍</div>
            </div>
            <input id="coordinates" type="text" readonly autocomplete="off" />
            <ul id="coord-results"></ul>
            <select id="label"></select>
            <div>
                <label for="image" translate>Photo</label>
                <input id="image" type="file" />
            </div>
            <input id="submit" type="submit" value="Submit" />
            <div class="extra-info">
                <div id="event-hint" class="hint" translate>Events disappear from the map after 24 hours</div>
                <div id="static-hint" class="hint" translate>Points of interest stay on the map indefinitely</div>
                <div id="show-help" translate>Help</div>
            </div>
        </div>
        <div id="error"></div>
        <div id="status"></div>
    </div>
</div>
<script>
const MAP_CENTER = {{ conf.MAP['CENTER'] }};
const MAP_ZOOM = {{ conf.MAP['ZOOM'] }};
const MAP_MIN_ZOOM = {{ conf.MAP['ZOOM_MIN']|default(10) }};
const MAP_MAX_ZOOM = {{ conf.MAP['ZOOM_MAX']|default(18) }};
const EXPIRE_TIME = {{ conf['EXPIRE_TIME']|default(60 * 60) }};
const VERSION = '{{ config.VERSION }}';
const SSE_URL = '{{url_for("sse.stream", channel=location)}}';
const HERE = '/{{ location }}';
</script>
<script src="{{ url_for('static', filename='dist/main.js') }}?{{config.VERSION}}"></script>
{% endblock %}

templates/panel.html
{% extends 'layout.html' %}

{% block content %}
<div id="panel">
    <div id="panel-errors"></div>
    <input id="key" type="text" placeholder="Key" autocomplete="off" />
    <div id="panel-main">
        <div id="manage-keys">
            <ul id="keys"></ul>
            <div class="actions">
                <span id="add-key" class="action">Add Key</span>
                <span id="add-prime-key" class="action">Add Admin Key</span>
            </div>
        </div>
        <div id="manage-pinned">
            <textarea id="pinned" placeholder="Pinned Message" autocomplete="off"></textarea>
            <div class="actions">
                <span id="set-pinned" class="action">Set Pinned Message</span>
            </div>
            <div id="set-pinned-status"></div>
        </div>
        <div id="manage-labels">
            <h2>Labels</h2>
            <ul id="labels"></ul>
            <div class="actions">
                <label for="label">Label:</label>
                <input id="label" type="text", autocomplete="off">
                <label for="icon">Icon:</label>
                <input id="icon" type="text", autocomplete="off" maxlength="2">
                <span id="add-label" class="action">Add Label</span>
            </div>
        </div>
        <div id="panel-logs">
            <h4>Admin logs</h4>
            <ul id="logs"></ul>
        </div>
    </div>
</div>
<script>
const HERE = '/{{ location }}';
</script>
<script src="{{ url_for('static', filename='dist/panel.js') }}"></script>
{% endblock %}